### ISSUE TITLE
lcd does not init on reboot

### ISSUE THREAD

**Issue by OAyomide** [mjhouse/ag-lcd#4] opened 2022-06-04 12:27 UTC
# Description
Following the example, it worked very fine (arduino uno) but it when i reboot my arduino (disconnect from power and power back on), it displays no text.

In order to be sure, i reproduced the same thing in the arduino IDE, and this issue doesn't exist. Also, in order to debug this issue, i added a simple blinking LED and tried again and it works (the LED blinks) but the display is still blank. Thats why I am pretty sure the issue is with this driver.

It'd be great to get pointers to implement a fix if you're too busy to work on something like this right now. I'd take the issue on, with guidance.

**Comment by mjhouse** [comment] 2022-06-04 16:39
@OAyomide Thanks man, I'm not sure what could cause that. Can you post the code that you saw this issue with so I can take a look?

**Comment by vcrn** [comment] 2022-08-30 06:42
In some cases, I have similar issues on Uno (haven't tried the crate yet on other models, but intend to do so). For example, I might flash a simple program to the Uno, and it works fine (in some cases, this doesn't even work, and I have to reconnect it and try it again). Then when I disconnect it and connect it back to the computer (or a pure power source) it sometimes works and sometimes not: again, it sometimes work to just reconnect it again. 

Once when I had this issue, where it wouldn't work even if I reflashed it with the same simple program, I added a LcdDisplay.clear() before printing the text, and it displayed it. This wasn't a reliable solution though, since most times it didn't seem to make a difference (in that simple code at least). I've also tried putting delays at different spots in the code, thinking that giving the Arduino some time before running certain commands might make it a bit more reliable, without finding a solution.

I think I've noticed that one of my more complex programs using ag-lcd is a lot more reliable when it comes to displaying the text. I'll try and add the repo to github as soon as possible and see if you could find what the potential cause could be. I'll see if I can notice any difference whether it's flashed from a Linux or Windows computer.

I also remember that when trying this crate out in the beginning, my code contained something like this:
```
lcd.print("First");
lcd.clear();
lcd.print("Second");
lcd.clear();
lcd.print("Third");
```
And only "Second" and "Third" would be displayed most of the times. This might have been a similar situation as the first case with the simple program that I described above.

Once I get hold of a Nano, I'll experiment with it too and see if this behavior can be replicated.

**Comment by vcrn** [comment] 2022-08-30 08:51
Maybe worth pointing out: I've only tried using half_bus()

**Comment by vcrn** [comment] 2022-08-30 15:11
Here's the relevant part of the "more complex code" which I mentioned earlier. I didn't want to clean away too much of the stuff that I've commented out, since some of them point toward issues I had in the past, like .with_blink(Blink::Off) and .with_cursor(Cursor::Off) not getting setting to off when setting up the LCD, which is why I set them to On or commented them out, just to set them to Off some lines down. I haven't noticed this issues in a long time though, which is why I've left all of those line as comments. This might be due to the same thing that's causing the issue of the screen not displaying text in other cases. notice also that when I'm printing, I'm always baking it in to the function lcd.clear_print():

```
fn main {    
    let dp = arduino_hal::Peripherals::take().unwrap();
    let pins = arduino_hal::pins!(dp);

    let mut adc = arduino_hal::Adc::new(dp.ADC, Default::default());

    let a0 = pins.a0.into_analog_input(&mut adc);
    let a1 = pins.a1.into_analog_input(&mut adc);

    let mut d8 = pins.d8.into_output();
    let mut d7 = pins.d7.into_output();

    let rs = pins.d12.into_output().downgrade();
    let en = pins.d10.into_output().downgrade();
    let d4 = pins.d5.into_output().downgrade();
    let d5 = pins.d4.into_output().downgrade();
    let d6 = pins.d3.into_output().downgrade();
    let d7 = pins.d2.into_output().downgrade();

    let delay = arduino_hal::Delay::new();
    let mut lcd: LcdDisplay<_, _> = LcdDisplay::new(rs, en, delay)
        .with_half_bus(d4, d5, d6, d7)
        .with_display(Display::On)
        //.with_blink(Blink::On) // Not affected by setting to Off.
        //.with_cursor(Cursor::On)
        .with_lines(ag_lcd::Lines::TwoLines)
        .build();
    //lcd.blink_off();
    //lcd.cursor_off();
    lcd.set_position(0, 0); // Might be unessacary

    [Calculations to get variables properly set]

    let mut serial = arduino_hal::default_serial!(dp, pins, 57600);

    // Gives output to computer, if connected
    ufmt::uwriteln!(&mut serial, "t_pump_on: {} ", t_pump_on).void_unwrap();
    ufmt::uwriteln!(&mut serial, "t_next_check_mins: {} ", t_next_check_mins).void_unwrap();
    ufmt::uwriteln!(
        &mut serial,
        "t_next_check_remainder_ms: {} ",
        t_next_check_remainder_ms
    )
    .void_unwrap();

    loop {
        d8.set_high(); // Turns on water sensor
        lcd.clear_print("Water & moisture", "sensors ON");
	...
	...
	[Some irrelevant code]
    	...
	...

    fn clear_print(&mut self, first_row: &str, second_row: &str)
    {
        self.clear();
        self.set_position(0, 0);
        self.print(first_row);
        delay_us(100); // A delay, even a very small one, is needed between printing and setting a new position. A bit unreliable how large delay needs to be.
        self.set_position(0, 1);
        self.print(second_row);
        self.set_position(0, 0)
    }
}
```

**Comment by mjhouse** [comment] 2022-08-31 11:02
The more complex code hasn't had a problem?

**Comment by vcrn** [comment] 2022-08-31 11:56
I can't remember the last time I had an issue with it. I do remember having problems with this code it was more simple though, but somewhere in the process the issue seems to have disappeared, or that the probability of it has decreased a lot (like the issue of the Blink and Cursor not getting set up correctly). 

I've noticed kind of the same thing with printing, waiting, setting a new position at the second row and then printing again: right now I wait 100 µs, but I started out waiting for a shorter time but had to increase it since I noticed that it too often didn't print correctly. As I increased it I noticed that the frequency of it not working correctly decreased, until I didn't notice the issue any longer when I had reached 100 µs.

I have no idea though if these things are caused by the same underlying issue.

**Comment by vcrn** [comment] 2022-08-31 12:28
Actually, now I ran into this issue again with the complex code. It's very hard to pin point what is causing this. I unplugged the Arduino from the computer (Windows), without the LCD displaying any text (even after waiting a while, which could be possible since it's running on loop where a print is being made every minute).

I tried reflashing it, flashing other code to it, reconnecting it and reflashing, plugging it into a powerbank, plugging it back into the computer and reflashing it. I went back and forth between flashing the complex code and a "Hello World" code, and and suddenly, (without having disconnected it for some flashings), it started to display the text.

It will be interesting to see if I can find the same behavior on a Nano using the same setup.

**Comment by mjhouse** [comment] 2022-08-31 18:58
It's all good. I don't have hardware set up to reproduce this stuff right now, so it's good to have an idea of what's been tried. Maybe a really long wait would make it reliable, and the shorter waits are only partially effective because of latency in the connection, or a faulty connection?

Anyway, if you find anything, let me know.

**Comment by vcrn** [comment] 2022-09-19 07:17
Something I noticed, which _might_ help: 

When I'm trying out some new code and the LCD doesn't init properly, I change the runner to something I now will give me an "not in sync error", which seems to reboot the board in a way that the LCD starts working. For example, when I want to flash a Uno board, I change the runner to "ravedude nano -cb 57600", which will use an incorrect bootloader, leading to 
```
    Finished dev [optimized + debuginfo] target(s) in 0.06s
     Running `ravedude nano -cb 57600 --port=/dev/ttyACM1 target/avr-atmega328p/debug/ag-lcd-print.elf`
       Board Arduino Nano
 Programming target/avr-atmega328p/debug/ag-lcd-print.elf => /dev/ttyACM1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
...
```
Which makes the LCD start flickering and initing correctly. Unfortunately, this isn't close to being considered a work around, just some trick I use when I don't want to go through the hassle of reconnecting the board.

I guess this might help in pinning down what the issue could be, or potentially finding a work around without really finding the underlying issue.

**Comment by vcrn** [comment] 2023-01-18 07:15
I've found a reliable and feasible workaround @mjhouse. This is run right after `.build()`:
```
        for _ in 0..3 {
            delay_ms(100);
            lcd.display_off();
            delay_ms(100);
            lcd.display_on();
        }
```
I haven't played around with the delays and number of loops too much, but I've haven't had any case of the LCD not initing with `for _ i in 0..2`, but I left it at `0..3` anyway. Some delay between `on` and `off` is necessary. 

Does this give you any idea of a solution that could be implemented in `ag-lcd`? The only thing I can think of right now is to add something similar at the end of `.build()` (which I'm not a fan of since it looks really ugly and feels like more of a workaround than a solution) or seeing if only adding a single delay somewhere in `build()` would help. Another option would be to add some short info about this in the README, but I have no idea how common this bug is: I've experienced it on different boards with different LCDs though.

**Comment by mjhouse** [comment] 2023-02-25 15:13
@vcrn Sorry I didn't respond. I don't know why, but Github decided your mention wasn't worth a notification for some reason. 

We could add a builder method to `LcdDisplay` like 

```
pub fn with_delay(mut self, value: usize) -> Self {
     delay_ms(value);
     self
}
```
And documentation on the method that recommends a value that should make screen init reliable. Then update examples/README etc to mention that the screen can sometimes need a pause in order to init. Thoughts?

**Comment by vcrn** [comment] 2023-02-25 15:35
@mjhouse No worries! That sounds like a good plan. I'll do some experimentation and see whether only a delay will suffice or if it's necessary to turn the screen off and on also. If this bug is solved via a builder method, turning the screen off and on seems more acceptable than if that code would be placed directly in `.build()` (since this would make the method `.with_display()` useless).

I'll get back to you with a suggestion!

**Comment by mjhouse** [comment] 2023-02-27 17:05
@vcrn Thanks!

**Comment by mjhouse** [comment] 2023-03-01 15:16
Thanks for the work, @vcrn I've merged the PR and I'm closing this issue. I think in the future, if we can find a way to make initialization reliable without that method, we can make another issue and handle it then, but this will do for now.

**Closed by mjhouse** 2023-03-01 15:16 UTC
Labels: bug
